apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: test-axl
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: test-axl
    #IF(#tests)
    apps.tanzu.vmware.com/has-tests: "true"
    #ELSE
    apps.tanzu.vmware.com/has-tests: "false"
    #ENDIF
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
